name: Jar Updater

on:  
  repository_dispatch:
    types: [new-jar]
    
  
permissions:
  contents: write

jobs:
  update-jar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: npm install
      run: |
        npm install
        npm install txml
        npm install -g vsce 
        npm install webpack
      
    - name: Log Info
      run: echo "ConfigId $CONFIGID, Version $VERSION"
      env:
        CONFIGID: ${{ github.event.client_payload.configId }}
        VERSION: ${{ github.event.client_payload.version }}

    - name: Run new-jar2.js
      run: node new-jar2.js configId=$CONFIGID version=$VERSION
      working-directory: resources/jars
      env:
        VERSION: ${{ github.event.client_payload.version }}
        CONFIGID: ${{ github.event.client_payload.configId }}
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: Add to CHANGELOG.md
      run: echo -e "- Update $CONFIGID to version $VERSION\n\n$(cat CHANGELOG.md)" > CHANGELOG.md
      env:
        VERSION: ${{ github.event.client_payload.version }}
        CONFIGID: ${{ github.event.client_payload.configId }}
    
    - name: Git Commit & Push
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add resources/jars/*.jar CHANGELOG.md
        git commit -m "[Automated action] Update $CONFIGID to version $VERSION"
        git push
      env:
        VERSION: ${{ github.event.client_payload.version }}
        CONFIGID: ${{ github.event.client_payload.configId }}
