name: 'test-changelog'
on:
  workflow_dispatch:

jobs:
  test-changelog:
    runs-on: ubuntu-latest
    steps:
      - run: touch change.md
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          fromTag: "v1.3.19"
          toTag: "v1.3.21"
          outputFile: './change.md'
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                    "title": "## ðŸ’¬ Other",
                    "labels": ["other"]
                },
                {
                    "title": "## ðŸ“¦ Dependencies",
                    "labels": ["dependencies"]
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: echo changelog
        run: |
          cat change.md
          
          
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: v1.3.21
          
      - run: echo ${{ steps.changelog.outputs.changes }}
